[build]
publish = "public"
command = "make production-build && cp _redirects dist/_redirects"

[build.environment]
HUGO_VERSION = "0.75.1"

[context.deploy-preview]
command = "make preview-build"

[context.branch-deploy]
command = "make preview-build"

[[redirects]]
  from = "/docs version=:version"
  to = "/archives/:version"
  status = 301
  force = true

